#!/bin/sh

cd basic
if sh testBasic > /dev/null; then true; else echo 'Test "basic" failed.'; exit 1; fi;
cd ..

cd libraries
if sh testLibraries > /dev/null; then true; else echo 'Test "libraries" failed.'; exit 1; fi;
cd ..

cd sharedLibrary
if sh testShLib > /dev/null; then true; else echo 'Test "shared library" failed.'; exit 1; fi;
cd ..

echo 'All Tests Successful!'
