#!/bin/sh

../../configure reconfigure cfgVars > configure
if sh configure; then true; else exit 1; fi;

# Fail if no makefile
if [ ! -f Makefile ]; then exit 1; fi;
make

# Fail if no executable
if [ ! -f version ]; then exit 1; fi;
if ./version; then true; else exit 1; fi;

make distclean
rm -f configure

exit 0;
